### ISSUE TITLE
Unable to classify old Rs 50 INR note correctly.

### ISSUE THREAD

**Issue by ami-agrl** [rowhitswami/Indian-Paper-Currency-Prediction#10]
The application is unable to classify the old currency notes correctly.

![image](https://user-images.githubusercontent.com/27025120/85883045-f435d900-b7fd-11ea-95bf-9203973d6b16.png)

**Comment by rowhitswami** [comment]
Hi @ami-agrl 
The model has been trained on new denomination of Indian currency.

Thank you
