### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Biman91** [rowhitswami/Indian-Paper-Currency-Prediction#11]
Hi
Hope you are doing good.
Kindly assist me the error that I send in attachment.
Thank You
****
![Error](https://user-images.githubusercontent.com/45765433/90660302-5db4ef80-e263-11ea-9d49-8ab0bac6d91b.JPG)

**Comment by rowhitswami** [comment]
Hi @Biman91,
The error message depicts that it couldn't upload your input image to S3 Bucket.
Please make sure that you exported the valid credentials for AWS S3 Bucket.
PS: You can also go through the issues in your Sentry to find the possible cause.

Thank you

**Comment by Biman91** [comment]
Thank you...
